name: Build and Deploy React App to EC2
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
jobs:
  # Job 1: Build the python app
  build:
    runs-on: ubuntu-latest
    name: Build python App

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
